"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _home_page from './home-page.bones.json'
import _latest_collection from './latest-collection.bones.json'
import _best_sellers from './best-sellers.bones.json'
import _about_page from './about-page.bones.json'
import _contact_page from './contact-page.bones.json'
import _cart_page from './cart-page.bones.json'
import _collection_grid from './collection-grid.bones.json'
import _login_page from './login-page.bones.json'
import _orders_page from './orders-page.bones.json'
import _place_order_page from './place-order-page.bones.json'
import _verify_page from './verify-page.bones.json'

registerBones({
  "home-page": _home_page,
  "latest-collection": _latest_collection,
  "best-sellers": _best_sellers,
  "about-page": _about_page,
  "contact-page": _contact_page,
  "cart-page": _cart_page,
  "collection-grid": _collection_grid,
  "login-page": _login_page,
  "orders-page": _orders_page,
  "place-order-page": _place_order_page,
  "verify-page": _verify_page,
})
